### model
model_name_or_path: /nfs4/wyz/merged_qwen2audio/lora_5l_merged
reward_model: "http"
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
reward_model_type: api

### dataset
dataset: weight
template: qwen2_audio
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2
remove_unused_columns: False
### output
output_dir: saves/ppo/test
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
